"""Domain layer - Core business logic, entities, and port interfaces."""

from agent_system.domain.entities import (
    Conversation,
    ConversationMetadata,
    KnowledgeGraph,
    KnowledgeNode,
    KnowledgeNodeType,
    LearnedPattern,
    Plan,
    StoredMessage,
    StoredPlanStep,
    User,
    UserPreferences,
)
from agent_system.domain.ports import (
    ClockPort,
    ConversationRepository,
    DeterministicIdGenerator,
    IdGeneratorPort,
    KnowledgeGraphPort,
    LLMConfig,
    LLMPort,
    LLMResponse,
    PlanRepository,
    Repository,
    SystemClock,
    UserRepository,
    UUIDGenerator,
)
from agent_system.domain.value_objects import (
    ConversationId,
    Entity,
    EntityType,
    Intent,
    IntentType,
    KnowledgeNodeId,
    Message,
    MessageContent,
    MessageId,
    MessageRole,
    PlanGoal,
    PlanId,
    PlanStatus,
    PlanStep,
    PlanStepId,
    Relationship,
    RelationType,
    StepStatus,
    Suggestion,
    ToolCall,
    UserId,
)

__all__ = [
    # Entities
    "User",
    "UserPreferences",
    "LearnedPattern",
    "Conversation",
    "ConversationMetadata",
    "StoredMessage",
    "Plan",
    "StoredPlanStep",
    "KnowledgeNode",
    "KnowledgeNodeType",
    "KnowledgeGraph",
    # Value Objects
    "UserId",
    "ConversationId",
    "MessageId",
    "PlanId",
    "PlanStepId",
    "KnowledgeNodeId",
    "MessageRole",
    "MessageContent",
    "ToolCall",
    "Message",
    "PlanStatus",
    "StepStatus",
    "PlanStep",
    "PlanGoal",
    "IntentType",
    "EntityType",
    "RelationType",
    "Intent",
    "Entity",
    "Relationship",
    "Suggestion",
    # Ports
    "Repository",
    "UserRepository",
    "ConversationRepository",
    "PlanRepository",
    "LLMPort",
    "LLMConfig",
    "LLMResponse",
    "KnowledgeGraphPort",
    "ClockPort",
    "SystemClock",
    "IdGeneratorPort",
    "UUIDGenerator",
    "DeterministicIdGenerator",
]
